default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sakabook_app_development
test:
  <<: *default
  database: sakabook_app_test
  
production:
  <<: *default
  database: sakabook_app_production
  username: sakabook_app
  password: <%= ENV['SAKABOOK_APP_DATABASE_PASSWORD'] %>
